---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Check if NGINX is installed'
      ansible.builtin.package:
        name: 'nginx'
        state: 'absent'
      register: __nginx_is_installed
      failed_when: __nginx_is_installed is changed
      check_mode: true
