---
- name: 'Debian | Configure the repository and install the NGINX package'
  become: true
  block:
    - name: 'Debian | Ensure the dependencies are installed'
      ansible.builtin.apt:
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'gnupg'
        update_cache: true
        cache_valid_time: 3600
        state: 'present'
      check_mode: false

    - name: 'Debian | Add the NGINX repository GPG key'
      ansible.builtin.apt_key:
        url: '{{ nginx_repository_gpgkey_url }}'
        keyring: '{{ __nginx_repository_gpgkey_keyring }}'
        state: 'present'

    - name: 'Debian | Add the NGINX repository'
      ansible.builtin.template:
        src: 'nginx.list.j2'
        dest: '/etc/apt/sources.list.d/nginx.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Debian | Pin the NGINX repository'
      ansible.builtin.copy:
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900
        dest: '/etc/apt/preferences.d/99-nginx'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Debian | Install the NGINX package'
      ansible.builtin.apt:
        name: "nginx{{ ('=' + nginx_package_version) if (nginx_package_version | length) else '' }}"
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (nginx_package_version | length) else 'latest' }}"
      ignore_errors: '{{ ansible_check_mode }}'
