---
- name: 'Configure YUM/DNF repository and install NGINX package'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: 'Add NGINX DNF/YUM repository'
      ansible.builtin.template:
        src: 'nginx.repo.j2'
        dest: '/etc/yum.repos.d/nginx.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install NGINX package'
      ansible.builtin.yum:
        name: "nginx{{ ('-' + nginx_version) if (nginx_version | length) else '' }}"
        allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
        update_cache: true
        state: "{{ 'present' if (nginx_version | length) else 'latest' }}"
