---
- name: 'Include the NGINX OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include tasks to install NGINX'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Include tasks to configure NGINX'
  ansible.builtin.import_tasks: 'configure.yml'
