---
- name: 'Install NGINX'
  ansible.builtin.include_tasks: "install-{{ ansible_facts['os_family'] }}.yml"
  when: nginx_setup in ['install', 'upgrade']

- name: 'Configure NGINX'
  ansible.builtin.include_tasks: 'configure.yml'
  when: nginx_setup in ['install', 'upgrade']

- name: 'Uninstall NGINX'
  ansible.builtin.include_tasks: 'uninstall.yml'
  when: nginx_setup in ['uninstall']
